#!/bin/bash

ID=1733223004
PREFIX="scalable24"


# main bucket for dataproc
DATAPROC_BUCKET_CLASS=regional
DATAPROC_BUCKET_NAME=${PREFIX}-dataproc-staging-bucket-${ID}
DATAPROC_BUCKET_ZONE=us-west1

# bucket for dataproc temporary files
DATAPROC_TMP_BUCKET_CLASS=regional
DATAPROC_TMP_BUCKET_NAME=${PREFIX}-dataproc-temp-bucket-${ID}
DATAPROC_TMP_BUCKET_ZONE=us-west1


# dataproc cluster
DATAPROC_CLUSTER_NAME=${PREFIX}-dataproc-cluster-${ID}
DATAPROC_CLUSTER_REGION=us-west1
DATAPROC_CLUSTER_ZONE=us-west1-b
DATAPROC_CLUSTER_NUM_WORKERS=3
DATAPROC_CLUSTER_MASTER_BOOT_DISK_SIZE=240
DATAPROC_CLUSTER_WORKER_BOOT_DISK_SIZE=240
DATAPROC_CLUSTER_MASTER_MACHINE_TYPE=n2-highmem-2
DATAPROC_CLUSTER_WORKER_MACHINE_TYPE=n2-highmem-2
#DATAPROC_SCALEUP_TO_NUMWORKERS=50
#DATAPROC_SCALEDOWN_TO_NUMWORKERS=2


# paths
PATH_SRC_JAR=../out/artifacts/scalable_jar/scalable.jar
PATH_SRC_DATASET=../src/main/resources/order_products.csv
PATH_DST_JAR=scalable.jar
PATH_DST_DATASET=order_products.csv
